name: Sample Project Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v5
      - name: Produce plugin
        run: "./gradlew :gradle-producer-build:publishToMavenLocal"
      - name: "Consume plugin"
        run: mvn -B -f sample/maven-consumer-build/pom.xml hello:sayhi
